### PR TITLE
enabled CPU inference

### PR DESCRIPTION
**Pull request by ohjho**
changed the code in a few places so that it's able to run on CPU

also changed the code formatting a little using [Black](https://github.com/psf/black)

### CODE REVIEW

**Comment by rdroste** [comment]
Thx for the contribution!

**Comment by ohjho** [comment]
and thanks for the great model!

i'm using it for a project and making a few additions to make inference of images and videos more streamlined, if you would like I could push those changes into here too

**Comment by rdroste** [comment]
Thanks for the suggestion. Feel free to open a PR once you have those changes. However, note that this repository needs to replicate the results from our paper, so I can't include changes that affect the accuracy. If the changes are too far-reaching, I can always link to your fork in the README.

**Comment by ohjho** [comment]
yes totally understand, the latest PR #21  only added inference functions, no subtractions, no modification of any of your existing methods or functions (aside from the code formatting for "better" readability).

I focused mostly on image inference for now, will make similar inference support for videos in a future PR

i'm currently testing the use of your model in combination of several different foundation models (e.g. SAM) to get salient objects

**Pull request merged**
